# Generated by Django 5.1.6 on 2025-03-09 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='compte',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ecriture',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='immobilisation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='plancomptable',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tresorerie',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(max_length=20)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.facture')),
            ],
        ),
    ]
